server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    response-cache-update-interval-ms: 10000
#    expected-client-renewal-interval-seconds: 15
  instance:
    hostname: localhost
spring:
  application:
    name: spring-cloud-balancing