spring:
  application:
    name: service-call
  main:
    allow-bean-definition-overriding: true
  cloud:
    loadbalancer:
      retry:
        enabled: true
        #        backoff:
        #          enabled: true
        #          min-backoff: 0s
        #          jitter: 1
        max-retries-on-next-service-instance: 3
        retry-on-all-operations: true
        avoid-previous-instance: false
  mvc:
    async:
      request-timeout: -1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 9099
